Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\Backend\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\controller\loginLogoutController.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\serializers.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\serializers.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\controller\loginLogoutController.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\controller\loginLogoutController.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\Backend\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/get-user/
"GET //users/get-user/ HTTP/1.1" 404 2130
Not Found: /users/get-user/
"GET //users/get-user/ HTTP/1.1" 404 2130
Bad Request: /choiceCenter/register/
"POST //choiceCenter/register/ HTTP/1.1" 400 77
Bad Request: /choiceCenter/register/
"POST //choiceCenter/register/ HTTP/1.1" 400 77
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /choiceCenter/register/
"POST //choiceCenter/register/ HTTP/1.1" 400 40
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
E:\Manzoor\Jsk\Backend\choiceCenter\models.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /choiceCenter/register/
"POST //choiceCenter/register/ HTTP/1.1" 400 40
E:\Manzoor\Jsk\Backend\choiceCenter\serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /choiceCenter/register/
Traceback (most recent call last):
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\transform.py", line 104, in query
    fields = _doc_cls._lookup_field(parts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\base\document.py", line 1140, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "username"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Manzoor\Jsk\Backend\choiceCenter\controller\loginLogoutController.py", line 23, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\Manzoor\Jsk\Backend\choiceCenter\serializers.py", line 21, in validate
    if query.count():
       ^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\queryset.py", line 143, in count
    return super().count(with_limit_and_skip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\base.py", line 432, in count
    collection=self._cursor.collection,
               ^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\base.py", line 1720, in _cursor
    self._cursor_obj = self._collection.find(self._query, **self._cursor_args)
                                             ^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\base.py", line 1769, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\visitor.py", line 91, in to_query
    query = query.accept(QueryCompilerVisitor(document))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\visitor.py", line 184, in accept
    return visitor.visit_query(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\visitor.py", line 80, in visit_query
    return transform.query(self.document, **query.query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WCD\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\queryset\transform.py", line 106, in query
    raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "username"
"POST //choiceCenter/register/ HTTP/1.1" 500 160580
